### ISSUE TITLE
Check if Eclipse Theia Cloud version can import SecHub reports

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub-plugin-vscode#3]
## Situation
When using eclipse theia as cloud variant  with SecHub plugin the import could be problematic because the import is done by `fs` inside  sechubModel.ts#loadFromFile

## Wanted
Check if this is a problem. If it is - create a new issue to solve the problem.

## Solution / How to
We can simple check this by using https://theia-ide.org/ (e.g. gitpod)  + install SecHub plugin there and do an import from report view.

**Comment by de-jcup** [comment]
I tried out with https://theia-ide.org/, the plugin was installable, unfortunately the file import does not work because of the file access. 

But we will implement api client calls later inside plugin, so reports can be fetched directly from server, which will also work inside cloud.

**Comment by Jeeppler** [comment]
@de-jcup did you use GitPod?

**Comment by de-jcup** [comment]
@Jeeppler : Unfortunately at https://theia-ide.org/ there is no longer the link for cloud variant directly on the main page available. As far as I remember there was a link directly on the website which was used by myself to install the plugin inside the cloud.

But using https://gitpod.io/#https://github.com/eclipse-theia/theia this works as well - sechub is installable as plugin but has got the mentioned problems.
