### ISSUE TITLE
Plugin not installable on Theia

### ISSUE THREAD

**Issue by Jeeppler** [Daimler/sechub-plugin-vscode#5]
The plugin cannot be installed on [Theia Blueprint](https://theia-ide.org/docs/blueprint_download/) version 1.12.1 (Alpha). Theia Blueprint is a desktop IDE based on Theia. The purpose of Theia Blueprint is to demonstrate the capabilities of Theia.

The problem is, that the SecHub plugin requires at least vscode 1.5.1:

package.json
~~~

	"engines": {
		"vscode": "^1.51.0"
	},
~~~

Theia 1.12.0+ is based on vscode 1.50: https://eclipse-theia.github.io/theia/docs/next/modules/plugin_ext_vscode.html. As a result, this plugin cannot be installed in Eclipse Theia.

**Comment by de-jcup** [comment]
I tried it out with Eclipse Theia Cloud and it worked out of the box - only file operation (load report from filesystem) did not work because being inside a browser.

**Comment by de-jcup** [comment]
Reading https://theia-ide.org/docs/blueprint_download.
I see:
> Eclipse Theia Blueprint is not a production-ready product. Therefore, it is also not meant to be a replacement for Visual Studio Code or any other IDE.

So we just wait until it's more "production-ready"

**Comment by Jeeppler** [comment]
@de-jcup Do you know the version number of Theia Eclipse Theia Cloud uses? Theia 1.12.1 is the latest release.

Did you install the plugin from OpenVSX?

**Comment by de-jcup** [comment]
@Jeeppler  Please look into #3 for details

**Comment by de-jcup** [comment]
@Jeeppler : Can we close this issue or is this still a problem?

**Comment by Jeeppler** [comment]
It is still a problem. Eclipse Theia Blueprint is now in Beta and they now show the VS Code API Version, they are compatible with.

Eclipse Theia Blueprint 1.17.2 is compatible with VS Code API Version 1.50.0 (see screenshot).

![eclipse_theia_blueprint_version](https://user-images.githubusercontent.com/2007739/132050056-b61d9a90-c2e1-413f-9f37-844f0da19305.png)

**Comment by Jeeppler** [comment]
Apparently, compatibility for [VS API version to 1.53.2](https://github.com/eclipse-theia/theia/pull/9959) was merged a few days ago into Eclipse Theia.

**Comment by Jeeppler** [comment]
Eclipse Theia 1.19 is now available for download. Eclipse Theia 1.19 supports the VSCode API version 1.53.2 and the SecHub plugin works well with it.
